docker github actions

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -10,46 +10,46 @@ jobs:
     steps:
       - name: Check out repository code
         uses: actions/checkout@v4
-      - run: sudo apt-get update
-      - run: sudo apt-get install g++ clang make cmake wget libgtest-dev
+      # - run: sudo apt-get update
+      # - run: sudo apt-get install g++ clang make cmake wget libgtest-dev
       
-      - name: Build
-        run: mkdir -p build && cd build && cmake .. && make
+      # - name: Build
+      #   run: mkdir -p build && cd build && cmake .. && make
       
-      - name: Start server
-        run: ./build/http-server &
+      # - name: Start server
+      #   run: ./build/http-server &
       
-      - name: Smoke test server
-        shell: bash
-        run: |
-          if ! wget --timeout=5 --tries=1 --spider http://localhost:7777/; then
-            exit 1
-          fi
+      # - name: Smoke test server
+      #   shell: bash
+      #   run: |
+      #     if ! wget --timeout=5 --tries=1 --spider http://localhost:7777/; then
+      #       exit 1
+      #     fi
       
-      - name: Unit Test
-        run: ./build/http-client UnitTest
+      # - name: Unit Test
+      #   run: ./build/http-client UnitTest
 
-      - name: Stop server
-        if: failure() || success()
-        run: pkill http-server
+      # - name: Stop server
+      #   if: failure() || success()
+      #   run: pkill http-server
 
-      - run: cd ..
+      # - run: cd ..
       
-      - name: Create debpkj
-        run: sh create_debpkg.sh
+      # - name: Create debpkj
+      #   run: sh create_debpkg.sh
       
-      - name: Upload artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: app
-          path: ./http-server-client-dcsa.deb
+      # - name: Upload artifact
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: app
+      #     path: ./http-server-client-dcsa.deb
         
-      - name: 'Upload Artifact'
-        uses: actions/upload-artifact@v4
-        with:
-          name: build
-          path: ./build
-          retention-days: 5
+      # - name: 'Upload Artifact'
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: build
+      #     path: ./build
+      #     retention-days: 5
 
 
 
@@ -65,6 +65,8 @@ jobs:
     steps:
       - name: Check out the repo
         uses: actions/checkout@v4
+        
+      - uses: ls -al
 
       - name: Download a single artifact
         uses: actions/download-artifact@v4
